In [132]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [134]:
df = pd.read_csv('Entities.csv')

In [135]:
df.head()

,Unnamed: 0,property_id,location_id,page_url,property_type,price,location,city,province_name,latitude,longitude,baths,purpose,bedrooms,date_added,agency,agent,Total_Area
0,0,237062,3325,https://www.zameen.com/Property/g_10_g_10_2_gr...,Flat,10000000,G-10,Islamabad,Islamabad Capital,33.679890,73.012640,2,For Sale,2,2/4/2019,NaN,NaN,1089.004
1,1,346905,3236,https://www.zameen.com/Property/e_11_2_service...,Flat,6900000,E-11,Islamabad,Islamabad Capital,33.700993,72.971492,3,For Sale,3,5/4/2019,NaN,NaN,15246.056
2,2,386513,764,https://www.zameen.com/Property/islamabad_g_15...,House,16500000,G-15,Islamabad,Islamabad Capital,33.631486,72.926559,6,For Sale,5,7/17/2019,NaN,NaN,2178.008
3,3,656161,340,https://www.zameen.com/Property/islamabad_bani...,House,43500000,Bani Gala,Islamabad,Islamabad Capital,33.707573,73.151199,4,For Sale,4,4/5/2019,NaN,NaN,10890.000
4,4,841645,3226,https://www.zameen.com/Property/dha_valley_dha...,House,7000000,DHA Defence,Islamabad,Islamabad Capital,33.492591,73.301339,3,For Sale,3,7/10/2019,Easy Property,Muhammad Junaid Ceo Muhammad Shahid Director,2178.008

In [136]:
df.shape

(168446, 18)

In [140]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168446 entries, 0 to 168445
Data columns (total 18 columns):
 #   Column         Non-Null Count   Dtype
---  ------         --------------   -----
 0   Unnamed: 0     168446 non-null  int64
 1   property_id    168446 non-null  int64
 2   location_id    168446 non-null  int64
 3   page_url       168446 non-null  object
 4   property_type  168446 non-null  object
 5   price          168446 non-null  int64
 6   location       168446 non-null  object
 7   city           168446 non-null  object
 8   province_name  168446 non-null  object
 9   latitude       168446 non-null  float64
 10  longitude      168446 non-null  float64
 11  baths          168446 non-null  int64
 12  purpose        168446 non-null  object
 13  bedrooms       168446 non-null  int64
 14  date_added     168446 non-null  object
 15  agency         124375 non-null  object
 16  agent          124374 non-null  object
 17  Total_Area     168446 non-null  float64
dtypes: float64(3), int64(6), object(9)
memory usage: 23.1+ MB

In [142]:
df = df.select_dtypes(exclude=['object'])
print(df)

        Unnamed: 0  property_id  location_id     price   latitude  longitude  \
0                0       237062         3325  10000000  33.679890  73.012640
1                1       346905         3236   6900000  33.700993  72.971492
2                2       386513          764  16500000  33.631486  72.926559
3                3       656161          340  43500000  33.707573  73.151199
4                4       841645         3226   7000000  33.492591  73.301339
...            ...          ...          ...       ...        ...        ...
168441      168441     17355248         6754  26500000  25.029909  67.137192
168442      168442     17355249          680  12500000  25.017951  67.136393
168443      168443     17355250         6757  27000000  25.015384  67.116330
168444      168444     17355251         6752  11000000  25.013265  67.120818
168445      168445     17355287        10045   9000000  25.113565  67.353811

        baths  bedrooms  Total_Area
0           2         2    1089.004
1           3         3   15246.056
2           6         5    2178.008
3           4         4   10890.000
4           3         3    2178.008
...       ...       ...         ...
168441      0         6   26136.096
168442      0         3    2178.008
168443      0         6   26136.096
168444      0         3   21235.578
168445      3         3   25591.594

[168446 rows x 9 columns]

In [144]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 168446 entries, 0 to 168445
Data columns (total 9 columns):
 #   Column       Non-Null Count   Dtype
---  ------       --------------   -----
 0   Unnamed: 0   168446 non-null  int64
 1   property_id  168446 non-null  int64
 2   location_id  168446 non-null  int64
 3   price        168446 non-null  int64
 4   latitude     168446 non-null  float64
 5   longitude    168446 non-null  float64
 6   baths        168446 non-null  int64
 7   bedrooms     168446 non-null  int64
 8   Total_Area   168446 non-null  float64
dtypes: float64(3), int64(6)
memory usage: 11.6 MB

In [146]:
df.isnull()

,Unnamed: 0,property_id,location_id,price,latitude,longitude,baths,bedrooms,Total_Area
0,False,False,False,False,False,False,False,False,False
1,False,False,False,False,False,False,False,False,False
2,False,False,False,False,False,False,False,False,False
3,False,False,False,False,False,False,False,False,False
4,False,False,False,False,False,False,False,False,False
...,...,...,...,...,...,...,...,...,...
168441,False,False,False,False,False,False,False,False,False
168442,False,False,False,False,False,False,False,False,False
168443,False,False,False,False,False,False,False,False,False
168444,False,False,False,False,False,False,False,False,False
168445,False,False,False,False,False,False,False,False,False

In [148]:
from sklearn.model_selection import train_test_split

In [150]:
x = df.iloc[:,df.columns!='price']
y = df.iloc[:,df.columns=='price']

In [152]:
print(x)

        Unnamed: 0  property_id  location_id   latitude  longitude  baths  \
0                0       237062         3325  33.679890  73.012640      2
1                1       346905         3236  33.700993  72.971492      3
2                2       386513          764  33.631486  72.926559      6
3                3       656161          340  33.707573  73.151199      4
4                4       841645         3226  33.492591  73.301339      3
...            ...          ...          ...        ...        ...    ...
168441      168441     17355248         6754  25.029909  67.137192      0
168442      168442     17355249          680  25.017951  67.136393      0
168443      168443     17355250         6757  25.015384  67.116330      0
168444      168444     17355251         6752  25.013265  67.120818      0
168445      168445     17355287        10045  25.113565  67.353811      3

        bedrooms  Total_Area
0              2    1089.004
1              3   15246.056
2              5    2178.008
3              4   10890.000
4              3    2178.008
...          ...         ...
168441         6   26136.096
168442         3    2178.008
168443         6   26136.096
168444         3   21235.578
168445         3   25591.594

[168446 rows x 8 columns]

In [154]:
print(y)

           price
0       10000000
1        6900000
2       16500000
3       43500000
4        7000000
...          ...
168441  26500000
168442  12500000
168443  27000000
168444  11000000
168445   9000000

[168446 rows x 1 columns]

In [156]:
xtrain, xtest, ytrain, ytest = train_test_split(x,y,test_size=0.5)

In [158]:
xtrain.head()

,Unnamed: 0,property_id,location_id,latitude,longitude,baths,bedrooms,Total_Area
5927,5927,9865522,93,31.462347,74.293642,7,6,3267.012
4661,4661,9371975,8917,31.436061,73.154585,5,5,1905.757
113631,113631,17015260,4083,31.418263,74.268087,0,10,10890.000
48990,48990,15334321,4196,31.442248,74.402375,4,4,2722.510
83628,83628,16647344,9612,31.588558,74.496808,3,3,1361.255

In [160]:
xtrain.shape

(84223, 8)

In [162]:
ytrain.head()

           price
5927    24000000
4661    20000000
113631  90000000
48990   22000000
83628    7000000

In [168]:
ytrain.shape

(84223, 1)

In [182]:
from sklearn.linear_model import LinearRegression

In [184]:
model = LinearRegression()

In [186]:
model.fit(xtrain,ytrain.values.ravel())

LinearRegression()

In [188]:
predict_output = model.predict(xtest)
print(predict_output)

[20840011.91847174 12581639.14268216  2044229.06132042 ...
  1154910.66649872 25678714.56087863 19679632.03059463]

In [190]:
from sklearn.metrics import accuracy_score

In [192]:
print(type(ytest), type(predict_output))
print(ytest[:5], predict_output[:5])

<class 'pandas.core.frame.DataFrame'> <class 'numpy.ndarray'>
           price
23664   30000000
9182    12500000
135372     50000
159057  10500000
107374   6860000 [20840011.91847174 12581639.14268216  2044229.06132042 20579189.23804218
 19628460.31532273]

In [194]:
predict_output = np.argmax(predict_output)

In [196]:
predict_output = model.predict(xtest)

In [198]:
print(predict_output.shape)
if len(predict_output.shape) > 1 and predict_output.shape[1] > 1:
    predict_output = np.argmax(predict_output, axis=1)

(84223,)

In [200]:
print("ytest unique values:", np.unique(ytest))
print("predict_output unique values:", np.unique(predict_output))

ytest unique values: [         0          1          3 ... 1200000000 1430000000 1450000000]
predict_output unique values: [-1.77689707e+08 -1.74394214e+08 -1.66256770e+08 ...  2.40343185e+09
  9.13120796e+09  3.29866224e+10]

In [211]:
ytest = ytest.astype(int)
predict_output = predict_output.astype(int)

In [213]:
acc=accuracy_score(ytest,predict_output)
print('The accuracy score for RF:',acc)

The accuracy score for RF: 0.0

In [215]:
from sklearn.metrics import r2_score
a=r2_score(ytest,predict_output)
print('The r2 score for RF:',a)

The r2 score for RF: 1.0000000080861455

In [217]:
from sklearn.metrics import mean_squared_error
mse=mean_squared_error(ytest,predict_output)
print('The mean squared error:',mse)

The mean squared error: -9657565.958776107